### ISSUE TITLE
Perhaps Port::Picker or Port::Selector is a more appropriate name?

### ISSUE THREAD

**Issue by perlancar** [JaSei/Port-Generator#2]
Just a suggestion from my perspective.

**Comment by JaSei** [comment]
I agree - `Port::Selector` sounds better.

**Comment by JaSei** [comment]
#4

**Comment by JaSei** [comment]
I renamed repo, release new distribution Port::Selector and in PAUSE delete Port::Generator files (I hope this is right workflow for renaming;))

**Comment by perlancar** [comment]
Yes, that's pretty much it. I rename distros all the time too :)
